/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder */

#ifndef _Included_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
#define _Included_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder_init
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
 * Method:    newDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder_newDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
 * Method:    mpgdecode
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder_mpgdecode
  (JNIEnv *, jobject, jobject, jint, jobject, jint);

/*
 * Class:     com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder_close
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder
 * Method:    exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer_ext_libmpg123_Mpg123Decoder_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
